name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  set-vars:
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.setvars.outputs.short_sha }}
    steps:
      - name: Set short SHA
        id: setvars
        run: echo "short_sha=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT

  frontend:
    needs: set-vars
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend/
          file: ./frontend/Dockerfile
          push: true
      - name: Set image tag
        id: tags
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "tag=${{ secrets.DOCKER_HUB_USERNAME }}/blogapp-frontend:prod-${{ needs.set-vars.outputs.short_sha }}" >> $GITHUB_OUTPUT
          else
            echo "tag=${{ secrets.DOCKER_HUB_USERNAME }}/blogapp-frontend:dev-${{ needs.set-vars.outputs.short_sha }}" >> $GITHUB_OUTPUT
          fi


  backend1:
    needs: set-vars
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push backend1 image
        uses: docker/build-push-action@v5
        with:
          context: ./backend1/
          file: ./backend1/Dockerfile
          push: true

      - name: Set image tag
        id: tags
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "tag=${{ secrets.DOCKER_HUB_USERNAME }}/blogapp-backend1:prod-${{ needs.set-vars.outputs.short_sha }}" >> $GITHUB_OUTPUT
          else
            echo "tag=${{ secrets.DOCKER_HUB_USERNAME }}/blogapp-backend1:dev-${{ needs.set-vars.outputs.short_sha }}" >> $GITHUB_OUTPUT
          fi


  backend2:
    needs: set-vars
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push backend2 image
        uses: docker/build-push-action@v5
        with:
          context: ./backend2/
          file: ./backend2/Dockerfile
          push: true

      - name: Set image tag
        id: tags
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "tag=${{ secrets.DOCKER_HUB_USERNAME }}/blogapp-backend2:prod-${{ needs.set-vars.outputs.short_sha }}" >> $GITHUB_OUTPUT
          else
            echo "tag=${{ secrets.DOCKER_HUB_USERNAME }}/blogapp-backend2:dev-${{ needs.set-vars.outputs.short_sha }}" >> $GITHUB_OUTPUT
          fi
    

  database:
    needs: set-vars
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push database image
        uses: docker/build-push-action@v5
        with:
          context: ./db/
          file: ./db/Dockerfile
          push: true
        
      - name: Set image tag
        id: tags
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "tag=${{ secrets.DOCKER_HUB_USERNAME }}/blogapp-database:prod-${{ needs.set-vars.outputs.short_sha }}" >> $GITHUB_OUTPUT
          else
            echo "tag=${{ secrets.DOCKER_HUB_USERNAME }}/blogapp-database:dev-${{ needs.set-vars.outputs.short_sha }}" >> $GITHUB_OUTPUT
          fi
    
